# Generated by Django 2.1.5 on 2019-08-28 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.CharField(max_length=100)),
                ('blood_pressure', models.CharField(max_length=100)),
                ('heart_problems', models.CharField(max_length=100)),
                ('drink', models.CharField(max_length=100)),
                ('smoke', models.CharField(max_length=100)),
                ('drugs', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history_completed',
            field=models.BooleanField(default=False),
        ),
    ]
