# Generated by Django 2.1.5 on 2019-08-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_auto_20190828_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=60)),
                ('disease', models.CharField(max_length=30)),
                ('starting_date', models.DateField()),
                ('last_visit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField()),
                ('medicine', models.CharField(max_length=50)),
                ('proress', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('test', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('bp', models.IntegerField()),
                ('symptoms', models.CharField(max_length=60)),
                ('disease', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='medic',
            name='visit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hmsapp.Visits'),
        ),
        migrations.AddField(
            model_name='labs',
            name='visit_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='hmsapp.Visits'),
        ),
    ]
