# Generated by Django 2.1.5 on 2019-08-30 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hmsapp', '0003_auto_20190829_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='proress',
            new_name='progress',
        ),
        migrations.AddField(
            model_name='case',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
