# Generated by Django 2.1.5 on 2019-08-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_medic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic',
            name='user',
        ),
    ]
