# Generated by Django 2.1.5 on 2019-09-01 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0006_remove_medic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='disease',
            field=models.CharField(default='popla', max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 18, 13, 30, 513346)),
        ),
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 18, 13, 30, 513346)),
        ),
    ]
