# Generated by Django 2.1.5 on 2019-09-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0011_auto_20190901_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
