# Generated by Django 2.1.5 on 2019-09-02 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0017_auto_20190902_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 20, 13, 4, 119890)),
        ),
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 2, 20, 13, 4, 118890)),
        ),
    ]
