# Generated by Django 2.1.5 on 2019-09-04 21:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0019_auto_20190902_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='visit_id',
        ),
        migrations.AlterField(
            model_name='case',
            name='disease',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 3, 7, 20, 772091)),
        ),
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 3, 7, 20, 772091)),
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labs',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.Visits'),
        ),
        migrations.AlterField(
            model_name='medic',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.Visits'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.Case'),
        ),
    ]
