# Generated by Django 2.1.5 on 2019-09-05 09:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0020_auto_20190905_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 14, 32, 21, 343605)),
        ),
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 14, 32, 21, 343605)),
        ),
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visits',
            name='case_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.Case'),
        ),
        migrations.AlterField(
            model_name='visits',
            name='disease',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='visits',
            name='medicine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='visits',
            name='progress',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='visits',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
