# Generated by Django 2.1.5 on 2019-09-05 09:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0023_auto_20190905_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='user',
        ),
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 14, 45, 53, 86786)),
        ),
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 14, 45, 53, 86786)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='case_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.Case'),
        ),
    ]
