# Generated by Django 2.1.5 on 2019-09-06 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0032_auto_20190906_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='case_id',
            new_name='case',
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='symptoms',
            new_name='current_status',
        ),
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 4, 2, 2, 853656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 4, 2, 2, 853656, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='bp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='visits',
            name='temperature',
            field=models.IntegerField(blank=True),
        ),
    ]
