# Generated by Django 2.1.5 on 2019-09-06 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0033_auto_20190906_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 4, 9, 0, 187147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 4, 9, 0, 187147, tzinfo=utc)),
        ),
    ]
