# Generated by Django 2.1.5 on 2019-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0036_auto_20190906_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='starting_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
