# Generated by Django 2.1.5 on 2019-09-06 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0037_auto_20190906_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='Date',
            new_name='date',
        ),
    ]
