# Generated by Django 2.1.5 on 2019-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0039_auto_20190906_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
