# Generated by Django 2.1.5 on 2019-09-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0040_auto_20190906_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
