# Generated by Django 2.1.5 on 2019-09-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0043_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labs',
            old_name='visit_id',
            new_name='visit',
        ),
    ]
