# Generated by Django 2.1.5 on 2019-09-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0045_current_cdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='cvisit',
            field=models.IntegerField(default=1),
        ),
    ]
