# Generated by Django 2.1.5 on 2019-09-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0047_auto_20190912_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
