# Generated by Django 2.1.5 on 2019-09-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0048_auto_20190912_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='test',
        ),
        migrations.AlterField(
            model_name='labs',
            name='test',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medic',
            name='medicines',
            field=models.TextField(max_length=100),
        ),
    ]
