# Generated by Django 2.1.5 on 2019-09-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0049_auto_20190914_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='price',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='medic',
            name='price',
            field=models.TextField(max_length=10),
        ),
    ]
